# Generated by Django 4.2.6 on 2024-01-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Email',
            field=models.EmailField(default='abc@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='ReEnterEmail',
            field=models.EmailField(default='abc@mail.com', max_length=254),
        ),
    ]
